apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temenos
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: temenos/jkube/
    repoURL: https://github.com/kevbrain/ocp-gitops-apps-deploy.git
    targetRevision: main
  syncPolicy: {}