apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: temenos-dev-eventlistener
  namespace: temenos-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: temenos-dev-trigger